services:
    trex:
        container_name: trex
        image: eisai/cisco-trex
        restart: "no"
        cap_add:
            - ALL
        privileged: true
        tty: true
        stdin_open: true
        command: ["-f", "/test.yaml", "-d", "10", "-l", "1000", "-m", "100"]
        volumes:
            - './test.yaml:/test.yaml'
            - './trex_cfg.yaml:/etc/trex_cfg.yaml'
            - '/lib/modules:/lib/modules:ro'
        devices:
            - /dev/uio0           # if uio driver
            - /dev/vfio/19        # if vfio driver
            # - /dev/uio1
            # - /dev/uio2
