name: Docker Image CI v2.87

on:
  workflow_dispatch:
    inputs:
      push:
        description: "Push the image"
        required: true
        type: boolean

jobs:
  build:
    name: build and push
    runs-on: ubuntu-latest
    env:
      GH_CI_PUSH: ${{ inputs.push }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run a multi-line script
        run: ./2.87/build.sh

